name: Build Game Executables

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: # Allows manual triggering

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pygame pyinstaller
          # Add any other dependencies your project needs

      - name: List directory contents for debugging
        run: |
          dir
          dir TetrisGame
          dir scenes

      - name: Build with PyInstaller
        shell: cmd
        run: >
          pyinstaller --name TetrisGame --windowed --onefile
          --add-data "TetrisGame/font;TetrisGame/font"
          --add-data "TetrisGame/img;TetrisGame/img"
          --add-data "scenes/avatars;scenes/avatars"
          --add-data "scenes/backgrounds;scenes/backgrounds"
          --add-data "scenes/avatars_data.json;scenes"
          main.py

      - name: Upload Windows Build
        uses: actions/upload-artifact@v4
        with:
          name: TetrisGame-Windows
          path: dist/TetrisGame.exe
