name: Build Game Executables

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pygame pyinstaller

      - name: Build Windows Executable (.exe)
        shell: cmd
        run: >
          pyinstaller main.py --name TetrisGame --windowed --onefile ^
          --add-data "TetrisGame/font;TetrisGame/font" ^
          --add-data "TetrisGame/img;TetrisGame/img" ^
          --add-data "scenes/avatars;scenes/avatars" ^
          --add-data "scenes/backgrounds;scenes/backgrounds" ^
          --add-data "scenes/avatars_data.json;scenes"

      - name: Upload Windows Executable
        uses: actions/upload-artifact@v4
        with:
          name: TetrisGame-Windows
          path: dist/TetrisGame.exe

  build-macos:
    runs-on: macos-12  # Ensures Intel-based runner for macOS
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Cache Python dependencies to speed up future builds
      - name: Cache Python dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-python-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-python-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pygame pyinstaller

      - name: Build macOS .app Bundle for Intel (x86_64 architecture)
        run: |
          arch -x86_64 pyinstaller main.py --name TetrisGame --windowed \
            --add-data "TetrisGame/font:TetrisGame/font" \
            --add-data "TetrisGame/img:TetrisGame/img" \
            --add-data "scenes/avatars:scenes/avatars" \
            --add-data "scenes/backgrounds:scenes/backgrounds" \
            --add-data "scenes/avatars_data.json:scenes"

      - name: Upload macOS .app Bundle
        uses: actions/upload-artifact@v4
        with:
          name: TetrisGame-macOS
          path: dist/TetrisGame.app
